### ISSUE TITLE
Suitability for online process simulation

### ISSUE THREAD

**Issue by mhechthz** [TuxRiders/freefem-intro#2]
Hi, this isn't an issue, but I didn't find a suitable e-mail address from you.

Do you have any idea, which codes/frameworks are suited for online process application. If I want to run a model related to a (production) process, I need to incorporate changing boundary conditions and parameters measured by sensors at the process. Reading static config files is not appropriate.

I currently focus on FENICS, since I have full control on dynamic boundary conditions and material data with this. With FreeFem I'm not sure, whether or not I can apply measured data from process dynamically to the FEM model and how a workflow would look like. Usually I have a process connection via messaging system and receive or send messages (with Python). With OpenFOAM I got the impression, that all is controlled via files and all is stored into files, which is not good for a dynamic process model.

So do you know, which of the systems is best suited for online process simulatiuon with dynamic parametetrs? Or do you now if there is a paper on this in the web?

Thanks in advance

P.S.: ... and thank you for the cool FreeFem intro

**Comment by mbarzegary** [comment]
it's a good question. I refer you to this short discussion on the FF community in this regard: https://community.freefem.org/t/interface-freefem-with-c/984
