### ISSUE TITLE
Example for dynamic use of FreeFem++ from python

### ISSUE THREAD

**Issue by MichaelHechtDH** [TuxRiders/freefem-intro#3]
I tried to solve this with ChatGPT but it becomes more and more confused. What I got so far is:

```
from pyfreefem import FreeFemRunner
import numpy as np

dt = 0.01;
nt = 100;

# Define your FreeFEM script
script = f'''
mesh Th = square(50, 50);
fespace Vh(Th, P1);
Vh u, v;

// Diffusion coefficient
real D = 0.1;

// Time discretization parameters
real dt = {dt};
int nt = {nt};

// Initial condition
u = 0;

// Define the problem
problem HeatEqn(u, v) = 
    int2d(Th)(
        u*v/dt + D * dx(u) * dx(v) + D * dy(u) * dy(v)
    )
    - int2d(Th)(
        u * v / dt
    )
    + on(1, u=0)   // Fixed Dirichlet boundary on three sides
    + on(2, u=0)   
    + on(3, u=0); 
'''

# Instantiate the FreeFEM runner
ff = FreeFemRunner(script)

# Python function to provide time-dependent Dirichlet boundary
def boundary_condition(t):
    return np.sin(t)

# Time stepping loop
for n in range(nt):
    t = n * dt

    # Get the boundary condition value
    bc_value = boundary_condition(t)

    # Set the time-dependent Dirichlet boundary condition
    script += f'on(4, u={bc_value})\n'  # Variable boundary on one side

    # Solve the problem
    script += 'HeatEqn\n'

# Run the script
ff.execute()

```

But I think this is not what I want/need. I want to run a FreeFem++ script in parallel to a production process, where I get every e.g. 10 seconds measurements. I want to put these measurements after a transformation as boundary conditions for my problem and calculation based on the results before the next 10 seconds. Something like (pseudo code):

```
myBasicScript = '''
...
...
...
'''
ffprob = makeFreeFemProblemFromBasicScript(myBasicScript)
while not finished:
    data = getDataFromProductionProcess()    
    bc = data2BC(data)
    ffprob.setBC(bc)
    ffprob.step(data.dt)
    state = ffprob.getCurrentVariables()
    info = state2information(state)
    sendInfoToProductionProcess(info)
```

We thought about using OpenFoam, but this is in my opinion totally not suited for online calculation. On the other hand, Fenics has been a good solution in the past, but all books with all examples are now outdated and Fenics became so complicated, that it is no longer suited for beginners. 

I really liked your FreeFem++ youtube lecture, but this last missing step.

**Comment by mbarzegary** [comment]
it's indeed an interesting problem, and I think I should make a video on it.

I have never worked with `pyfreefem`, so I cannot help on that, but you can easily call FreeFEM codes from an external code written in any programming language like Python or C++ via a system call. This kind of offline linking is always possible, in which you call FF executable to solve a problem and write the solution to the disk (you wait for it), and then, you collect the result in your own code (in this case the production process) and continue with it. this can be done by passing command line arguments to the FF code, which is described here: https://youtu.be/algfmHKNsX4?list=PL6fjYEpJFi7Wu9ZFlak7r0QgrF0aNi8H1&t=842. For a real-world example of this, yoo can refer to [this software](https://github.com/mbarzegary/BioDeg-UI) which is built completely based on such a concept. 

For time-dependent or variable BC, you may have a look at the discussion here: https://community.freefem.org/t/time-dependent-dirichlet-bc/987

**Comment by MichaelHechtDH** [comment]
A video would be cool. 

Nevertheless, what is really "ugly" from IT point of view, is generating files for every timestep and "comunicate" via harddisk. This is pain for my harddisk. The pythonic and modern IT way would be to call FreeFem from Python library like pyfreefem (if this works). The other way would be to create a memory based directory (ramdisk), so all happens in the memory. Writing on disk is the worst possible solution (but sometime the only working one). 

I'm eagerly waiting for a video on this topic.

Thank You in advance.

**Comment by mbarzegary** [comment]
That's very true. Unfortunately, as you said, that's the only workaround for some scenarios. A great solution for all-in-memory communications is the coupling libraries, the best example of which [preCICE](https://precice.org/), but the bad news is FreeFEM doesn't have a preCICE adapter (yet).

Just as something else you may be interested to check out in this regard: [StabFem project](https://stabfem.gitlab.io/StabFem) provides an interface to FF in MATLAB. I've never worked with it, so I don't know how it works (like if they have some tricks to communicate with FF in memory or not), but it may give you some ideas on how to do it or maybe use this library for your automation project (which needs switching to MATLAB/Octave from Python in this case).
